resolver: lts-7.14
packages:
- '.'
- location:
    git: https://github.com/positiondev/larceny.git
    commit: 51b9c6945ef656fb489b2fc1a035439f9fb56885
  extra-dep: true
# - '../larceny/'
- location:
      git: https://github.com/positiondev/fn.git
      commit: 5898878bff740665986bb49c4bdc48c11646c3b1
  subdirs:
    - fn
  extra-dep: true
extra-deps:
- logging-3.0.4
- heroku-0.1.2.3
- wai-session-clientsession-0.1
- cereal-text-0.1.0.2
- digestive-functors-0.8.1.1
- rivet-adaptor-postgresql-0.1.0.0
- rivet-core-0.2.0.0
- html-entities-1.1.2
