resolver: lts-6.6
packages:
- '.'
- location:
    git: https://github.com/positiondev/larceny.git
    commit: 580ef43758efd79f8aec31375a8d89a3f403ed6e
  extra-dep: true

extra-deps:
- directory-1.2.6.3
- logging-3.0.4
- heroku-0.1.2.3
- wai-session-clientsession-0.1
- cereal-text-0.1.0.2
