resolver: lts-6.6
packages:
- '.'
- 'convert'
- location:
    git: https://github.com/positiondev/larceny.git
    commit: 72de344930d5d71e0a3f12f12fdc1bb80fe896cb
  extra-dep: true

extra-deps:
- directory-1.2.6.3
- logging-3.0.4
- heroku-0.1.2.3
- wai-session-clientsession-0.1
- cereal-text-0.1.0.2
